services:
  hems-core:
    container_name: hems-core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    env_file:
      - .env
    restart: unless-stopped